### ISSUE TITLE
READMEファイルに説明文を記載する

### ISSUE THREAD

**Issue by norotime** [amnmsht/event_app#1]
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by amnmsht** [comment]
READMEファイルにこのアプリの説明文を記入しました。

**Comment by norotime** [comment]
@amnmsht ここだけリンクがおかしいので、修正をお願いします。
![2018-03-25 21 29 21](https://user-images.githubusercontent.com/7435505/37874974-9ccc5770-3073-11e8-8d8a-29e78fbe5999.png)

**Comment by amnmsht** [comment]
取り急ぎ修正しました。
