### ISSUE TITLE
明らかにクラスとメソッドの構造がおかしいため補正する

### ISSUE THREAD

**Issue by norotime** [amnmsht/event_app#2]
https://github.com/amnmsht/event_app/blob/57a1c85899afc782abdf281bb0da6fc6a72b317c/app/controllers/contacts_controller.rb#L2

**Comment by amnmsht** [comment]
contacts_controllre.rbの記述が誤っていたので修正しました。

**Comment by norotime** [comment]
@amnmsht 良くなったような気がしましたが、まだチェックが必要そうです。

**Comment by amnmsht** [comment]
もう一度見直してみます。ご確認ありがとうございます。
