### ISSUE TITLE
文字列よりもシンボルの方が高速なためシンボル化する

### ISSUE THREAD

**Issue by norotime** [amnmsht/event_app#4]
https://github.com/amnmsht/event_app/blob/57a1c85899afc782abdf281bb0da6fc6a72b317c/app/controllers/contacts_controller.rb#L18

**Comment by amnmsht** [comment]
出力するアクションを指定する方法として、文字列の他にシンボルが使えることを理解しました。

**Comment by norotime** [comment]
@amnmsht シンボルで記載してくださいねー。

render 'new'

じゃなくて

render :new

**Comment by amnmsht** [comment]
実感としてもアクションの表示が速いと感じました。
