### ISSUE TITLE
Rubyコーディング規約を完全に遵守する

### ISSUE THREAD

**Issue by norotime** [amnmsht/event_app#5]
https://shugo.net/ruby-codeconv/codeconv.html

**Comment by norotime** [comment]
@amnmsht インデントがずれているのがものすごく気になります。全部直していただけますか？
https://github.com/amnmsht/event_app/blob/6a07f706879906e7a3427f74af18e11fbbdd8699/app/controllers/entries_controller.rb#L4

**Comment by norotime** [comment]
@amnmsht 
https://github.com/amnmsht/event_app/blob/6a07f706879906e7a3427f74af18e11fbbdd8699/app/controllers/entries_controller.rb#L4
このコードの end はどれだと認識していますか？
コーディング規約、ちゃんと読んでいますか？

**Comment by norotime** [comment]
特にブロックの章を入念に見てください。

**Comment by amnmsht** [comment]
もう一度やり直してみました。

**Comment by norotime** [comment]
@amnmsht どうやり直したのかを、念のため、説明していただけますか？

**Comment by amnmsht** [comment]
複数のクラスの区切には空行を挿入するべきと考えていたため、def create以降の最初のendの後に空行を挿入していました。そうではなく、このブロックから始まるコードのendはelse以降にあるendであると考え、空行を削除しました。

**Comment by norotime** [comment]
@amnmsht まだご理解がいただけていなかったため、下記に答えを明示します。

誤）
```
    entry = current_user.entries.build do |t|
    t.event_id = params[:event_id]
    t.comment = params[:entry][:comment]
  end
```

正）
```
    entry = current_user.entries.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:entry][:comment]
    end
```

何が違うかをよく確認していただけますか？また、構造を正しく捉えてください。

**Comment by norotime** [comment]
@amnmsht 
>複数のクラスの区切には空行を挿入するべき

ファイルの中にクラスは複数記述しません。
クラスとはどのことを指していますか？
クラスとメソッドとは何かを教えてください。

**Comment by norotime** [comment]
（基礎を正しく理解していただけないと、応用ができないため、少し厳しめに記載しています。）

**Comment by norotime** [comment]
@amnmsht また、entryには、複数のインスタンスが格納されるのであれば、entriesなど複数形にする必要もありそうです。

**Comment by amnmsht** [comment]
クラスとはどのことを指していますか
クラスとメソッドとは何かを教えてください。

クラスとは定義的には、データと処理をひとまとめにした設計図にあたるもの。今回の場合は、class EntriesControllerから最終行のendまで該当すると考えています。
メソッドは、やりたいことを実行する関数のようなものと理解しています。defで始まりendで終了します。今回の場合は、def createから次のメソッドが始まる手前のendがその範囲になります。

**Comment by amnmsht** [comment]
entryの記述も適切ではありませんでした。複数にする必要がありました。

**Comment by amnmsht** [comment]
コードはもう一度確認のうえ、修正します。ご指摘いただいてとおり、基本が理解できておりません。もう一度学習します。

**Comment by amnmsht** [comment]
下記のように修正しました。

def create
    entry = current_user.entries.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:entry][:comment]
    end

**Comment by amnmsht** [comment]
entries_controllerのインデントを修正しました。entryの記述については、影響する部分を確認します。
